name: trycut3d
description: A new Flutter project.

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  model_viewer_plus: ^1.9.3
  google_fonts: ^6.1.0
  lottie: ^3.3.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/fundo_app.png
    - assets/images/avatar.png
    - assets/models/avatar_negro.glb
    - assets/models/avatar_branco.glb
    - assets/models/avatar_pardo.glb
    - assets/animations/raio_titulo.json

  fonts:
    - family: Orbitron
      fonts:
        - asset: assets/fonts/Orbitron-VariableFont_wght.ttf
